apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-container
  name: frontend-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
      - image: impiyush83/zilean-frontend
        name: frontend-container
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: GATEWAY_SERVICE_URL
            value: "http://gateway-container:5006/"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-container
  name: frontend-container
spec: 
  type: LoadBalancer
  selector: 
    app: frontend-container
  ports:
  - port: 3000
    targetPort: 3000