apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-container
  name: gateway-container
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gateway-container
  template:
    metadata:
      labels:
        app: gateway-container
    spec:
      containers:
      - image: impiyush83/main-plot-service
        name: gateway-container
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb-container:27017"
          - name: AWS_ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef: 
                name: awskey
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: 
              secretKeyRef: 
                name: awssecret
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: "us-east-1"
          - name: S3_HOST
            value: "https://s3.amazonaws.com"
          - name: S3_BUCKET
            value: "plots-1"
          - name: USE_LOCAL
            value: "False"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-container
  name: gateway-container
spec: 
  type: LoadBalancer
  selector: 
    app: gateway-container
  ports:
  - port: 5006
    targetPort: 5006
    nodePort: 30010

---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: gateway-container-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: gateway-container
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 50