apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-container
  name: gateway-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-container
  template:
    metadata:
      labels:
        app: gateway-container
    spec:
      containers:
      - image: impiyush83/main-plot-service
        name: gateway-container
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        env:
          - name: KAFKA_BROKER_URL
            value: kafka-container:9092
          - name: AUDIT_SERVICE
            value: http://audit-container:5001
          - name: SESSION_SERVICE
            value: http://session-container:5004
          - name: USER_SERVICE
            value: http://user-container:5005  
          - name: PLOT_SERVICE
            value: http://plot-container:5002

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-container
  name: gateway-container
spec: 
  type: LoadBalancer
  selector: 
    app: gateway-container
  ports:
  - port: 5006
    targetPort: 5006
    nodePort: 30010

---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: gateway-container-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: gateway-container
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 50