---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-container
  template:
    metadata:
      labels:
        app: kafka-container
        id: "0"
    spec:
      containers:
      - name: kafka-container
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: 1
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-container:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-container:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-container
  labels:
    name: kafka-container
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer