apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafpq-container
  name: kafpq-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafpq-container
  template:
    metadata:
      labels:
        app: kafpq-container
    spec:
      containers:
      - image: impiyush83/main-kafka-plot-queue
        name: kafpq-container
        imagePullPolicy: Always
        env:
          - name: KAFKA_BROKER_URL
            value: http://kafka-container:9092
          - name: PLOT_SERVICE
            value: "http://plot-container:5002"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: kafpq-container
spec:
  clusterIP: None