apiVersion: v1
kind: Secret
metadata:
  name: kafka-client-config
  namespace: default
type: Opaque
data:
  kafka.properties: Ym9vdHN0cmFwLnNlcnZlcnM9a2Fma2EuY29uZmx1ZW50LnN2Yy5jbHVzdGVyLmxvY2FsOjkwNzEKc2VjdXJpdHkucHJvdG9jb2w9UExBSU5URVhU

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: 
spec:
  serviceName: kakfa-container
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: kakfa-container
  template:
    metadata:
      labels:
        app: kakfa-container
    spec:
      containers:
      - name: kakfa-container
        image: confluentinc/cp-kafka:latest
        command:
        - /bin/sh
        - -c
        - |
          kafka-producer-perf-test \
            --topic audit-queue  \
            --record-size 64 \
            --throughput 1 \
            --producer.config /mnt/kafka.properties \
            --num-records 230400
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
          readOnly: true
        resources:
          requests:
            memory: 1024Mi
            cpu: 500m
      volumes:
        - name: kafka-properties
          secret:
            secretName: kafka-client-config

---

apiVersion: v1
kind: Service
metadata:
  name: kakfa-container
spec:
  clusterIP: None

---

apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: data-retrieval-queue
  namespace: default
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"

---

apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: audit-queue
  namespace: default
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"


---

apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: plot-queue
  namespace: default
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"