apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container-claim0
  name: mongodb-container-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi

---


apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container
  name: mongodb-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-container
    spec:
      containers:
        - image: mongo
          name: mongodb-container
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-container-claim0
      restartPolicy: Always
      volumes:
        - name: mongodb-container-claim0
          persistentVolumeClaim:
            claimName: mongodb-container-claim0

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-container
  name: mongodb-container
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-container
