---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  zookeeper-container
  template:
    metadata:
      labels:
        app:  zookeeper-container
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: 2181
            - name: ZOOKEEPER_TICK_TIME
              value: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-container
  labels:
    app: zookeeper-container
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper-container