version: 2.1

jobs:
    build:
        working_directory: ~/zilean/user-service
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - run: cd user-service &&  pip install pipenv && pipenv install -r requirements.txt && pipenv run python app.py