version: 2.1

jobs:
    build:
<<<<<<< HEAD
        working_directory: ~/zilean/user-service
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - run: cd user-service && pip install -r requirements.txt && pytest tests
=======
        working_directory: ~/zilean/plot-service
        docker:
            - image: "cimg/python:3.8.10"
        steps:
            - checkout
            - run: cd plot-service && pip install -r requirements.txt && pytest tests
>>>>>>> main-plot-service
