version: 2.1

jobs:
    build:
        working_directory: ~/zilean/frontend
        docker:
            - image: "cimg/node:10.16.0"
        steps:
            - checkout
            - run: cd frontend && npm install
