version: 2.1

jobs:
    build:
        working_directory: ~/zilean/gateway-service
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - run: cd gateway-service && pip install -r requirements.txt && pytest tests