version: 2.1


orbs:
  docker: circleci/docker@1.4.0

workflows:
  zilean-workflow:
    jobs:
      - zilean-job:
          context:
            - build-env-vars
            - docker-hub-creds
            - zilean

jobs:
    zilean-job:
        working_directory: ~/zilean/kafka-data-retrieval-queue
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            - run: docker push $DOCKERHUB_USERNAME/kafka-data-retrieval-queue:latest
            - run: docker logout
            - run: cd kafka-data-retrieval-queue && pip install -r requirements.txt