version: 2.1

jobs:
    build:
        working_directory: ~/zilean/audit-service
        docker:
            - image: "cimg/node:10"
        steps:
            - checkout
            - run: npm install
            - run: npm run start