version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - zilean

jobs:
    build:
        working_directory: ~/zilean/audit-service
        docker:
            - image: "cimg/node:16.14.2"
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - run: cd audit-service && docker build -t $DOCKER_USERNAME/$CIRCLE_BRANCH:latest .
            - run: docker push $DOCKER_USERNAME/$CIRCLE_BRANCH:latest
            - run: docker logout
            - run: cd audit-service && npm install && npm run tests
