version: 2.1



workflows:
  build:
    jobs:
      - build:
          context:
            - zilean

jobs:
  build:
    working_directory: ~/zilean/session-service
    docker:
      - image: "cimg/openjdk:11.0.13"
    steps:
      - add_ssh_keys:
            fingerprints:
              - "a9:e3:cc:51:62:6b:9c:36:e0:51:a6:5f:ec:27:30:8f"

      - checkout
      - run: cd session-service && mvn package -Dmaven.test.skip -f pom.xml
      - setup_remote_docker
      - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - run: cd session-service && docker build -t $DOCKER_USERNAME/$CIRCLE_BRANCH:latest .
      - run: docker push $DOCKER_USERNAME/$CIRCLE_BRANCH:latest
      - run: docker logout
      - run:
          name: Deploy
          command: |
            ssh -oStrictHostKeyChecking=no $JETSTREAM_USER bash -c '  
                sudo su
                cd Zilean/dp
                kubectl delete -f session-container.yaml
                kubectl apply -f session-container.yaml'
      
