version: 2.1

jobs:
    build:
        working_directory: ~/zilean/user-service
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - run: cd user-service && pip install -r requirements.txt && python app.py