version: 2.1

jobs:
    build:
        working_directory: ~/zilean/kafka-plot-queue
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - run: cd kafka-plot-queue && pip install -r requirements.txt