version: 2.1

jobs:
    build:
        working_directory: ~/zilean/data-retrieval-service
        docker:
            - image: "cimg/python:3.8.10"
        steps:
            - checkout
            - run: cd data-retrieval-service && pip install -r requirements.txt && pytest tests