version: 2.1



workflows:
  build:
    jobs:
      - build:
          context:
            - zilean

jobs:
    build:
        working_directory: ~/zilean/gateway-service
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - run: cd gateway-service && docker build -t $DOCKER_USERNAME/$CIRCLE_BRANCH:latest .
            - run: docker push $DOCKER_USERNAME/$CIRCLE_BRANCH:latest
            - run: docker logout
            - run: cd gateway-service && pip install -r requirements.txt && pytest tests
            - run: ssh -o StrictHostKeyChecking=no $JETSTREAM_USER
            - run: $JETSTREAM_PASSPHRASE
            - run: sudo su