version: 2.1

jobs:
    build:
        working_directory: ~/zilean/kafka-data-retrieval-queue
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
            - run: docker push impiyush83/kafka-data-retrieval-queue:latest
            - run: docker logout
            - run: cd kafka-data-retrieval-queue && pip install -r requirements.txt