version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - zilean

jobs:
    build:
        working_directory: ~/zilean/kafka-data-retrieval-queue
        docker:
            - image: "cimg/python:3.10.4"
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - run: docker build -t $DOCKER_USERNAME/zilean-kafdq .
            - run: docker push $DOCKER_USERNAME/kafdq:latest
            - run: docker logout
            - run: cd kafka-data-retrieval-queue && pip install -r requirements.txt