version: 2.1

jobs:
    build:
        working_directory: ~/zilean/audit-service
        docker:
            - image: "cimg/node:16.14.2"
        steps:
            - checkout
            - run: cd audit-service && npm install && npm run start