version: '3.1'

services:

  mongodb-container:
    image: mongo
    restart: always
    container_name: mongodb-container
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017
