version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './dockervolume/postgres:/data/db'
    environment:
      POSTGRES_PASSWORD: 'audit_service_test'
      POSTGRES_DB: 'audit_service_test'
      POSTGRES_USER: 'audit_service_test'
