---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audit-container
  name: audit-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audit-container
  template:
    metadata:
      labels:
        app: audit-container
    spec:
      containers:
      - image: impiyush83/zilean-audit
        name: audit-container
        imagePullPolicy: Always
        # resources: 
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits: 
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5001
        env:
            - name: DB_CONNECTION
              value: postgres
            - name: DB_CONNECTION_POOL_MAX_CONNECTIONS
              value: "6"
            - name: DB_CONNECTION_POOL_MIN_CONNECTIONS
              value: "1"
            - name: DB_DATABASE
              value: audit_service_test
            - name: DB_HOST
              value: postgresql-container
            - name: DB_PASSWORD
              value: audit_service_test
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: audit_service_test
            - name: SQL_LOGGING_ENABLED
              value: "true"
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: audit-container
  name: audit-container
spec: 
  type: LoadBalancer
  selector: 
    app: audit-container
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
