apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-retrieval-container
  name: data-retrieval-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-retrieval-container
  template:
    metadata:
      labels:
        app: data-retrieval-container
    spec:
      containers:
      - image: impiyush83/main-data-retrieval-service
        name: data-retrieval-container
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb-container:27017"
          - name: KAFKA_BROKER_URL
            value: kafka-container:9092

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-retrieval-container
  name: data-retrieval-container
spec: 
  type: LoadBalancer
  selector: 
    app: data-retrieval-container
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30011

---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: data-retrieval-container-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: data-retrieval-container
#   minReplicas: 1
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 50

