apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafaq-container
  name: kafaq-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafaq-container
  template:
    metadata:
      labels:
        app: kafaq-container
    spec:
      containers:
      - image: impiyush83/main-kafka-audit-queue
        name: kafaq-container
        imagePullPolicy: Always
        env:
          - name: KAFKA_BROKER_URL
            value: kafka-container:9092 ## https://kafka-container:9092 gives error --> "ValueError: invalid literal for int() with base 10: '//kafka-container'"
          - name: AUDIT_SERVICE
            value: http://149.165.152.187:5001
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: kafaq-container
spec:
  clusterIP: None