# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: kafka-broker0
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#         id: "0"
#     spec:
#       containers:
#       - name: kafka
#         image: wurstmeister/kafka
#         # image: confluentinc/cp-kafka:latest
#         ports:
#         - containerPort: 9092
#         env:
#         - name: KAFKA_ADVERTISED_PORT
#           value: "9092"
#         # - name: KAFKA_ADVERTISED_HOST_NAME
#         #   value: "sb-kafka"
#         - name: KAFKA_ADVERTISED_HOST_NAME
#         value: "kafka-container"
#         - name: KAFKA_ZOOKEEPER_CONNECT
#           value: zoo1:2181
#         - name: KAFKA_BROKER_ID
#           value: "0"
#         - name: KAFKA_CREATE_TOPICS
#           value: "image:1:1"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sb-kafka
#   labels:
#     name: kafka
# spec:
#   ports:
#     - port: 9092
#       name: kafka-port
#       protocol: TCP
#   selector:
#     app: kafka
#     id: "0"
#   type: LoadBalancer


kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: kafka-container
  name: kafka-container
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka-container
        id: "0"
  template:
    metadata:
      labels:
        app: kafka-container
        id: "0"
    spec:
      containers:
      - name: kafka-container
        # image: wurstmeister/kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-container:9092,PLAINTEXT_HOST://localhost:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: '1'
        # - name: KAFKA_ADVERTISED_PORT
        #   value: "30718"
        # - name: KAFKA_ADVERTISED_HOST_NAME
        #   value: kafka-container
        # - name: KAFKA_CREATE_TOPICS
        #   value: admintome-test:1:1
        # - name: KAFKA_LISTENERS
        #   value: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-container
  labels:
    name: kafka-container
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-container
    id: "0"
  type: LoadBalancer
