apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafpq-container
  name: kafpq-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafpq-container
  template:
    metadata:
      labels:
        app: kafpq-container
    spec:
      containers:
      - image: impiyush83/main-kafka-plot-queue:latest
        name: kafpq-container
        imagePullPolicy: Always
        # command: ["sh","-c"]
        # args: ["while true; do echo 'yo' && sleep 5; done;"]
        env:
          - name: KAFKA_BROKER_URL
            value: kafka-container:9092 ## https://kafka-container:9092 gives error --> "ValueError: invalid literal for int() with base 10: '//kafka-container'"
          - name: PLOT_SERVICE
            value: http://149.165.152.187:30002

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: kafpq-container
spec:
  clusterIP: None

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kafpq-container
#   name: kafpq-container
# spec: 
#   type: LoadBalancer
#   selector: 
#     app: kafpq-container
#   ports:
#   - port: 5011
#     targetPort: 5011
#     nodePort: 30021