apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-container
  name: user-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-container
  template:
    metadata:
      labels:
        app: user-container
    spec:
      containers:
      - image: impiyush83/main-user-service:latest
        name: user-container
        imagePullPolicy: Always
        ports:
        - containerPort: 5005
        env:
          - name: MONGO_URI
            value: "mongodb://mongodb-container:27017"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-container
  name: user-container
spec: 
  type: LoadBalancer
  selector: 
    app: user-container
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 30005


