# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: zookeeper-deployment-1
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: zookeeper-1
#   template:
#     metadata:
#       labels:
#         app: zookeeper-1
#     spec:
#       containers:
#         - name: zoo1
#           # image: digitalwonderland/zookeeper
#           image: confluentinc/cp-zookeeper:latest
#           ports:
#             - containerPort: 2181
#           env:
#             - name: ZOOKEEPER_ID
#               value: "1"
#             - name: ZOOKEEPER_SERVER_1
#               value: zoo1
#             - name: ZOOKEEPER_CLIENT_PORT
#               value: "2181"
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: zoo1
#   labels:
#     app: zookeeper-1
# spec:
#   ports:
#     - name: client
#       port: 2181
#       protocol: TCP
#     - name: follower
#       port: 2888
#       protocol: TCP
#     - name: leader
#       port: 3888
#       protocol: TCP
#   selector:
#     app: zookeeper-1


kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: zookeeper-container
  name: zookeeper-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-container
  template:
    metadata:
      labels:
        app: zookeeper-container
    spec:
      containers:
      - name: zookeeper-container
        # image: digitalwonderland/zookeeper
        image: confluentinc/cp-zookeeper:latest
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: '2181'
          - name: ZOOKEEPER_TICK_TIME
            value: '30000'
          # - name: ZOOKEEPER_ID
          #   value: "1"
          # - name: ZOOKEEPER_SERVER_1
          #   value: zoo1

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper-service
spec:
  ports:
  - port: 2181
    targetPort: 2181
    # protocol: TCP
  # - name: follower
  #   port: 2888
  #   protocol: TCP
  # - name: leader
  #   port: 3888
  #   protocol: TCP
  selector:
    app: zookeeper-container



