version: '3.0'
services:
  awsLocalstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - AWS_RAWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"